### ISSUE TITLE
Create a boilerplate - documentation

### ISSUE THREAD

**Issue by dhoko** [FreshRSS/Extensions#1]
Hello,

We need a boilerplate in order to create a new extension, or at least some documentation:
- List of hooks/actions
- How to interact with the core
- How to create a simple ext
- etc.

Thanks :)

**Comment by marienfressinaud** [comment]
I will have a look to this this afternoon. I don't want to spend too much time on it so I think I'll write it in French if it doesn't matter for you ;). Translation can come later!

**Comment by marienfressinaud** [comment]
Here is the first draft: https://github.com/FreshRSS/documentation/blob/master/fr/02_Documentation_d%C3%A9veloppeurs/03_Backend/05_%C3%89criture_d%27extensions.md

I have not finished the document (and I have roughly spoken about extensions) but tell me if it's clear enough for the moment.

**Comment by dhoko** [comment]
We do not know how to dev extensions :/ There are many things but not about extensions :/

**Comment by marienfressinaud** [comment]
I know, it was only a beginning, I don't have so much time to spend on documentation (I would so). I'll try to continue this week.

**Comment by kevinpapst** [comment]
+1 for more documentation. 
You have a great software, but you will get so much more attraction with a bigger "pool" of extensions ... which would be much easier to develop with more background information.

**Comment by kevinpapst** [comment]
I would suggest that we close this ticket, as there was more documentation published in the meantime, see https://freshrss.github.io/FreshRSS/en/developers/03_Backend/05_Extensions.html

If someone wants more information, a new ticket should be raised?!
