### ISSUE TITLE
Image proxy guide

### ISSUE THREAD

**Issue by prysme01** [FreshRSS/Extensions#10]
Hello 
I would like to setup an image proxy cache that could be user by freshrss image proxy extension, but I don't know how to do it. Is it possible to have a guide that explain what to do ?
thanks in advance.

**Comment by Alkarex** [comment]
Hello @prysme01 
Sorry for the delay - I somehow overlooked the notification.
There is a brief explanation on https://github.com/FreshRSS/Extensions/blob/master/xExtension-ImageProxy/README.md . Maybe @Frenzie could point to additional resources if needed?

**Comment by Frenzie** [comment]
The script simply sticks a URL processed with [rawurlencode](http://php.net/manual/en/function.rawurlencode.php) at the end of whatever you set up as the proxy.

https://github.com/FreshRSS/Extensions/blob/e820c338b2a37a4ac01a578722644b32ba927aea/xExtension-ImageProxy/extension.php#L32

I suppose you could add an option for other URL encoding schemes than RFC 3986 (like Base64), but unless there's a ready-made proxy that uses a different encoding scheme I don't see why you would. :-)

**Comment by prysme01** [comment]
@Alkarex I've already seen this documentation, but it is really not clear on how to setup an image proxy.
I would like to do it because my company is filtering a lot of URL and I would like freshrss to keep the content and also the image.

**Comment by Alkarex** [comment]
@prysme01 Is your problem related to installing a proxy (if yes, which one have you picked?), or configuring FreshRSS to use it? See also Frenzie's comment just above.

**Comment by prysme01** [comment]
I've set this URL https://images.weserv.nl/i but I doesn't work
The image is not displayed
src is https://images.weserv.nl/images.neozone.org%2F2016%2F12%2FWorld-View-Entreprise-ballon-espace-003.jpg

**Comment by Alkarex** [comment]
Try https://images.weserv.nl/?url=images.neozone.org%2F2016%2F12%2FWorld-View-Entreprise-ballon-espace-003.jpg

**Comment by prysme01** [comment]
Good this works.
Why don't set this up by default with the extension and add a small documentation to advise to change it if the users want to use his own proxy ?

**Comment by Frenzie** [comment]
That is in fact exactly the way it works. :-P

**Comment by prysme01** [comment]
@Frenzie by default without any URL in the configuration it doesn't work.
On my setup I had to put https://images.weserv.nl/?url=
So there is no default configuration.

**Comment by Frenzie** [comment]
By default any extension you add is disabled.

**Comment by obyy** [comment]
Yeah this work for me without configuration.

In your readme you say : " For example, in Apache you could use mod_rewrite to set up a simple proxy "

Do you have an example ? I don't understant how you can do this with just a rewrite rule.
thx 👍

**Comment by Frenzie** [comment]
I've never done so myself, but a quick peek at (
https://duckduckgo.com/?q=apache+reverse+proxy&t=ffsb&ia=web)[the top
search results for "Apache reverse proxy"] suggests it shouldn't be too
hard with mod_proxy.
