### ISSUE TITLE
Place for listing FreshRSS extensions

### ISSUE THREAD

**Issue by kevinpapst** [FreshRSS/Extensions#11]
Hi there, 
while searching for FreshRSS extensions I stumbled upon this repository, but couldn't find any other resource.
I would suggest to have a place where users can link their own extensions.
This is not only a shameless try to drop a link to my [freshrss youtube extension](https://github.com/kevinpapst/freshrss-youtube) ;-) but I believe that the FreshRSS community would benefit from it.

The easiest way for the start could be to include a new section in this repositories README with links to "third party extensions". I could sent in a PR if you like the idea.

Any other suggestions?

**Comment by Alkarex** [comment]
Yes indeed, adding a link from the readme would be a good start. PR welcome :-)

**Comment by kevinpapst** [comment]
Here you go: #12

**Comment by Alkarex** [comment]
Ah, this is also good, but I though of a link in FreshRSS's readmes https://github.com/FreshRSS/FreshRSS

**Comment by kevinpapst** [comment]
Alright - I can do that as well. Do you want:
1. keep this PR and also link from the main repo to this one
2. or do you want to have a new "extensions" section in the main README with a link to this repo and to the external URLs (and close this PR unmerged)
?

**Comment by Alkarex** [comment]
Yes for 1, please :-)

**Comment by kevinpapst** [comment]
I believe, that is a special case for branching of from master?!?

**Comment by kevinpapst** [comment]
Here it is: FreshRSS/FreshRSS#1389
