### ISSUE TITLE
Manage applied custom styles in CustomCSS

### ISSUE THREAD

**Issue by icubyx** [FreshRSS/Extensions#110]
When i apply a custom CSS using CustomCSS, they disappear and if I want to change or remove the custom CSS, I don't know how to. It will be great if one can see the CSS they have applied and change it.

**Comment by Frenzie** [comment]
I'm not sure I quite understand. They're in the same text box you put them
in?

**Comment by icubyx** [comment]
Oh Sorry. I now can see them. Some time ago, the css just disappeared when I tried viewing it in Vivaldi browser, no matter how much I refreshed the page.
