### ISSUE TITLE
CustomCSS - need to add "!important" to CSS elements

### ISSUE THREAD

**Issue by gabrielcossette** [FreshRSS/Extensions#13]
Hi,

I'm using the CustomCSS extension and I need to add "!important" at the end of each elements in order to work. Otherwise, they are overridden.

Is that the expected behavior? If yes, I suggest we add this important precision to the README.

Thanks!

**Comment by Alkarex** [comment]
Hello,
Could you please provide an example of rule for which you need to add `!important`?
In CSS, the most precise rule wins, or the last rule when several rules are equally precise. I suspect the CSS rules you are trying to add are not precise enough (less qualified).

**Comment by gabrielcossette** [comment]
Here's an example:

A custom rule:
```
.content {
    min-height: auto !important;
}
```
To replace:
```
.content {
    min-height: 20em;
```
set by "p/themes/base-theme/template.css"

As they are equally precise, I assume the normal behaviour would be that CustomCSS would override it. Maybe it's not loaded after template.css?

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/Extensions/issues/13 (upcoming FreshRSS 1.7.0). Tests of /dev branch welcome.
