### ISSUE TITLE
Extensions from Portainer not Appearing

### ISSUE THREAD

**Issue by daveroxs12** [FreshRSS/Extensions#131]
I installed extensions into /portainer/Files/AppData/Config/FreshRSS/www/freshrss/extensions

Inside of the folder is the "README.md" file, stating the extension should be placed into this file.

However, the extensions are not appearing under the extensions tab on my FreshRSS page.

Why can I do about this?

**Comment by math-GH** [comment]
This should be the correct path:

`freshrss/extensions/extension1/`

in `extension1` you will find f.e. `README.md` and `metadata.json`

**Comment by daveroxs12** [comment]
After SSHing into the freshrss/extensions, there is no extension1 folder.

Should I create the extension1folder and manually create a metadata.json file and copy and paste the contents from freshrss? 

Thanks for your help so far.

**Comment by math-GH** [comment]
Let me help you.

Which extension do you want install?

**Comment by daveroxs12** [comment]
I want to add the FreshRSS_Extension-ReadingTime by Lapineige. (Link Here - https://framagit.org/Lapineige/FreshRSS_Extension-ReadingTime)

**Comment by math-GH** [comment]
OK. Here is how it works:

create a new folder in `freshrss/extensions/` (folder name f.e. `ReadingTime`). Copy the files into this new folder.

Result:
`freshrss/extensions/ReadingTime/`:
- `static`
- LICENCE
- README.md
- extension.php
- metadata.json

**Comment by daveroxs12** [comment]
All right. Thank You for your assistance. I successfully installed the extension

**Comment by math-GH** [comment]
@daveroxs12 : I would recommend to use this extension repository: https://github.com/FreshRSS/Extensions/tree/master/xExtension-ReadingTime because it looks like a bit more maintained

**Comment by daveroxs12** [comment]
Ok. Will do.
