### ISSUE TITLE
xExtension-Youtube update

### ISSUE THREAD

**Issue by ImAReplicant** [FreshRSS/Extensions#133]
Hi,
I updated the Youtube/Peertube extension to correct the display of Peertube feeds. Here is the link: https://framagit.org/ImAReplicant/freshrss-youtube
Can I make a PR to replace the @kevinpapst extension because it is no longer maintained?

**Comment by kevinpapst** [comment]
Thats the spirit of open source. You never tried to send a PR, or did I miss it?

**Comment by ImAReplicant** [comment]
You didn't miss anything, I didn't dare to do a PR without asking :)
I'll do it ASAP. Thx
