### ISSUE TITLE
(Windows)(Docker) Please. Explain me from A to Z as if I were a retard.

### ISSUE THREAD

**Issue by TheMystery28** [FreshRSS/Extensions#138]
Explain me from A to Z as if I were a retard.
After installing FreshRSS with docker pull freshrss/freshrss and running it . I have been trying for days to get the extensions to show up. For me the Blacklist is too important a feature not to use .

I don't see how to put the extensions folder in the vhdx virtual machine and I don't understand the examples given on the sites I visited.

**Comment by Frenzie** [comment]
Which examples do you mean? These? https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#quick-run
