### ISSUE TITLE
Could I rename my third-party extension?

### ISSUE THREAD

**Issue by aidistan** [FreshRSS/Extensions#142]
Sorry to ask but I wonder if it's possible to rename my published third-party extension?

I am considering changing it from a verb-object structure to a noun, namely from "[Sync with System Theme](https://github.com/aidistan/freshrss-extensions)" to "Theme Mode Synchronizer".

**Comment by Frenzie** [comment]
I don't see why not?

**Comment by Alkarex** [comment]
The only difficulty might be with existing users, risking having two copies of the extension

**Comment by aidistan** [comment]
Got it. Thanks for the reply~

**Comment by aidistan** [comment]
Is there anyone could merge #143 to update the README.md?
