### ISSUE TITLE
Custom CSS in Docker

### ISSUE THREAD

**Issue by Bitbitti** [FreshRSS/Extensions#146]
How do I customize the style of a feed category so that the feeds don't show cover art and have a larger youtube player?
freshrss runs in docker

**Comment by math-GH** [comment]
Have you installed the CustomCSS extension?
How experienced are you with CSS?
Could you please share an example feed and a screenshot? It would help to understand what you mean and speak about the same thing.

**Comment by math-GH** [comment]
check if it works for you

```
.content .enclosure {
  display: none;
}
```

**Comment by Bitbitti** [comment]
it works perfectly.
I modified the command like this: .content .enclosure-thumbnail {
  display: none;
}
now how do i enlarge the youtube player?

**Comment by Bitbitti** [comment]
thank you all for your help,
to enlarge the youtube player, i used the command:
audio, iframe, embed, object, video {
	max-width: 500%;
width: 400px;
	height: 600px;
}
