### ISSUE TITLE
Reading time extension error

### ISSUE THREAD

**Issue by svemoe** [FreshRSS/Extensions#148]
Reading time extension is not working for me.
In firefox console I get the error message `Uncaught TypeError: document.querySelector(...).childNodes[0].childNodes[2] is undefined`.
Maybe something in FreshRSS layout changed?
Anyone else have this problem?
When I switch to mobile view it's fine.

**Comment by Frenzie** [comment]
At a quick glance I think that'll work as intended if you use ` document.querySelector("#" + reading_time.flux.id + " ul.horizontal-list li.item.website span") ` but I'm not 100% sure what it used to look like.

**Comment by math-GH** [comment]
@svemoe Which FreshRSS version do you use? 1.20.2?

ping @lapineige as author of this extension.

**Comment by lapineige** [comment]
It doesn't work for me on 1.20 indeed… I recently updated, I had no time to fix it.
I will try to take a look in the coming days, @svemoe don't hesitate to ping me if nothing happened in let's say 2 weeks :)

**Comment by Alkarex** [comment]
Ping @lapineige ;-)

**Comment by lapineige** [comment]
Fixed by #156 ?
