### ISSUE TITLE
TTRSS API: getUnread() not implemented

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/Extensions#15]
Hello,

TTRSS-API seems not to be working. In the app "NewsJet" I get:
```
Expected a boolean but was STRING at line 1 column 82 path $.content[0].marked
```
and in official TTRSS app I can see it synces the list of feeds but not the contents of them (it says "error, check journal" but don't know where it is located).

In FreshRSS log I have:
```
[Mon, 08 May 2017 10:29:13 +0000] [warning] --- TTRSS API: getUnread() not implemented
[Mon, 08 May 2017 10:29:38 +0000] [warning] --- TTRSS API: getUnread() not implemented```
```

Greader clone API is working OK.

**Comment by Alkarex** [comment]
For reference: https://play.google.com/store/apps/details?id=mobi.newsjet.rss

**Comment by Alkarex** [comment]
Work continues in https://github.com/FreshRSS/FreshRSS/pull/1526
