### ISSUE TITLE
ImageProxy error with manual feed update

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/Extensions#159]
I recently put this extension in freshrss.
later when some of my feeds had net issue, I tried to manually update feed and it wouldnt work. I see in freshrss logs this:
`
 [error] 1050#1050: *120108 FastCGI sent in stderr: "PHP message: PHP Deprecated:  mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /freshrss/extensions/xExtension-ImageProxy/extension.php on line 115" while reading upstream, client: 192.168.1.101, server: odroid, request: "GET /i/?a=normal&rid=649a85245b418&next=1687842604845323&state=2&ajax=1 HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "myhost"`

**Comment by Frenzie** [comment]
Could you try `htmlentities($content, ENT_COMPAT, 'UTF-8')`?

**Comment by rezad1393** [comment]
I disable and removed both that exention for that error but the issue with manual update was because of autoTTL extension.
so I removed both.
even removing both addon it took a while (maybe ttl had to expire) so that I could again manually update feeds that has erros.


maybe I should just try with this picture addon and test your solution.

will try and report back but it may takes some time because I dont know if it only happens with some feeds and I dont know if the issue happens with only with manual feed update or not. and right now I dont completely remember the feeds that has those error.

so I will add the extension again and will track it here.
thank you for the answer.

**Comment by rezad1393** [comment]
is this it?
`		$doc->loadHTML(htmlentities($content, ENT_COMPAT, 'UTF-8')?);`

I get this error:
`FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected token ")"`

**Comment by Frenzie** [comment]
Some related discussion here: https://www.drupal.org/project/smart_trim/issues/3342481

It seems you can also do something like this instead to work around the problem, which if it works would probably be better anyway:

```
$dom = new DOMDocument();
$dom->loadHTML('<meta http-equiv="Content-Type" content="text/html; charset=utf-8">' . $profile);
echo $dom->saveHTML();
```

**Comment by rezad1393** [comment]
> Some related discussion here: https://www.drupal.org/project/smart_trim/issues/3342481
> 
> It seems you can also do something like this instead to work around the problem, which if it works would probably be better anyway:
> 
> ```
> $dom = new DOMDocument();
> $dom->loadHTML('<meta http-equiv="Content-Type" content="text/html; charset=utf-8">' . $profile);
> echo $dom->saveHTML();
> ```

by the way have to tested this?

**Comment by Frenzie** [comment]
I can't test right now, but
```
$doc->loadHTML(htmlentities($content, ENT_COMPAT, 'UTF-8'));
```

with

```
$doc->loadHTML('<meta http-equiv="Content-Type" content="text/html; charset=utf-8">' . $content);
```

**Comment by rezad1393** [comment]
I replaced it and it seems to work but last time it was working with feeds already gotten and later it showed its error.
so maybe I need to wait for a feed to give an error to be sure.

if this is an official extension, will you be testing this with unit testing to make sure it is ok and not bug introducing?
and maybe post the result (official update) here?

**Comment by Frenzie** [comment]
This won't affect anything related to refreshing or updating feeds. It's only called before display.

As an aside, at present it still works. PHP calls it an error to draw attention to it but it's just a deprecation notice.

**Comment by Frenzie** [comment]
Some random Chinese stuff seems to display okay so I figure it should be good.
![image](https://github.com/FreshRSS/Extensions/assets/202757/1ed93b57-069e-4b89-901b-e01f367d9060)
