### ISSUE TITLE
Flaresolverr Extension

### ISSUE THREAD

**Issue by widowild1** [FreshRSS/Extensions#163]
FreshRSS plugin that provides cloudflare puzzle solving via flaresolverr 

https://github.com/ravenscroftj/freshrss-flaresolverr-extension

**Comment by Alkarex** [comment]
Anyone to make a PR? :-)

**Comment by widowild1** [comment]
Bonjour, @Alkarex, merci je ne le savais pas.

**Comment by Alkarex** [comment]
> Bonjour, @Alkarex, merci je ne le savais pas.

Je voulais dire qu'il faut l'ajouter :-) Exemple pour une autre extension https://github.com/FreshRSS/Extensions/pull/137/files
