### ISSUE TITLE
Invalid JSON in extensions' metadata.json

### ISSUE THREAD

**Issue by eht16** [FreshRSS/Extensions#175]
https://github.com/FreshRSS/Extensions/commit/5a1be06d01b2ca0dd57aea02aa095be259cb39e0 broke the metadata.json of a few extensions with invalid JSON.
The new third level in the version number must be quoted as string because currently it would be interpreted as a float with two decimal digits.

Currently, the extensions fail to load with:
```
FreshRSS[45]: [X] [Sat, 16 Sep 2023 14:16:18 +0200] [warning] --- `/var/www/FreshRSS/extensions/xExtension-QuickCollapse/metadata.json` is not a valid metadata file
FreshRSS[45]: [X] [Sat, 16 Sep 2023 14:16:18 +0200] [warning] --- `/var/www/FreshRSS/extensions/xExtension-ReadingTime/metadata.json` is not a valid metadata file
FreshRSS[45]: [X] [Sat, 16 Sep 2023 14:16:18 +0200] [warning] --- `/var/www/FreshRSS/extensions/xExtension-StickyFeeds/metadata.json` is not a valid metadata file
```

**Comment by Alkarex** [comment]
Thanks for the bug report. Should be fixed by 
https://github.com/FreshRSS/Extensions/pull/176 + https://github.com/FreshRSS/Extensions/commit/79211d30aafd6e41141df0490a21dcef1e239285
Tests welcome
