### ISSUE TITLE
Recent commit (ce44911) breaks CustomCSS (possibly others)

### ISSUE THREAD

**Issue by edwrap** [FreshRSS/Extensions#184]
Commit: https://github.com/FreshRSS/Extensions/commit/ce44911e325dc1291bf91e11b41e16e9e1698cc9

Reposting my comment from the commit for added visibility:
The CustomCSS extension is broken after this commit (possibly others, too, but this is the only one I use). On a new install of FreshRSS today, CustomCSS config page is blank, and enabling the extension breaks FreshRSS entirely. Downloaded version immediately before this commit and it works as usual

**Comment by Alkarex** [comment]
Thanks for the heads up.
What FreshRSS version on which setup (Docker image, PHP version...)

**Comment by edwrap** [comment]
This is working with the FreshRSS edge release - my mistake!

**Comment by Alkarex** [comment]
Let me try to make a better fix. It should work at least with the `latest` release as well. But I can see that there is first a bit of cleaning to do...

**Comment by rfog** [comment]
The problem is still with FreshRSS 1.22.1 and last commit (6148b58). After uploading the extension and refresh, you get an Error 500. I don't know how to get my PHP version as I'm using a 3rd party hosting.

**Comment by Alkarex** [comment]
@rfog Please try with our `edge` version of FreshRSS, which should fix the issue

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/releases/tag/1.23.1
