### ISSUE TITLE
[Bug] xExtension-ColorfulList: JavaScript error on pages that have no feed articles

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/Extensions#187]
ping @shinemoon 

Extension: xExtension-ColorfulList

FreshRSS version: current 1.22.2-dev edge

JavaScript error in the browser console (tested with Firefox 120 on Win10)
![grafik](https://github.com/FreshRSS/Extensions/assets/1645099/c3c8dd25-bf8a-4688-9394-e88c91ec2191)

Error appears on every page, that does not show the feeds.
No error: normal view
Error: subscription manage page. Or: Extension page

**Comment by shinemoon** [comment]
Fix created as above... please help to check. thx.

**Comment by math-GH** [comment]
fine
