### ISSUE TITLE
xExtensions CustomCSS - Crashes after moved into extension directory

### ISSUE THREAD

**Issue by Gjessing1** [FreshRSS/Extensions#189]
Running a FreshRSS instance, with version 1.22.1. But when i clone the xExtension-CustomCSS folder into my Extension folder the program is no longer available in the browser.  Other extensions seems to work fine, and as soon as I remove the folder the instance is again available in the browser. I have tried disabling all other folders to check for cross compatibility, but get the same problem. The docker instance does not seem to crash.

User extensions running and working fine:
 ⚙️ Fixed Nav Menu
 ⚙️ Keep Folder State
 ⚙️ Reddit Image
 ⚙️ Smart Mobile Menu
 ⚙️ Title-Wrap
 ⚙️ Touch Control

**Comment by Alkarex** [comment]
Hello,
Please see https://github.com/FreshRSS/FreshRSS/discussions/5904

**Comment by Gjessing1** [comment]
Thank you, that answers my questions perfectly. Looking forward to the desember release then 😊

**Comment by rezad1393** [comment]
I have updated this extension to new version "version": "0.4" and it crashes my freshrss.

```
2024/02/15 09:06:39 [error] 852#852: *5382 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Minz_Session::paramString() in /freshrss/extensions/xExtension-CustomCSS/extension.php:12
Stack trace:
#0 /freshrss/lib/Minz/ExtensionManager.php(263): CustomCSSExtension->init()
#1 /freshrss/lib/Minz/ExtensionManager.php(279): Minz_ExtensionManager::enable()
#2 /freshrss/app/FreshRSS.php(64): Minz_ExtensionManager::enableByList()
#3 /freshrss/p/i/index.php(55): FreshRSS->init()
#4 {main}
  thrown in /freshrss/extensions/Extension-CustomCSS/extension.php on line 12" while reading response header from upstream, client: 192.168.1.101, server: odroid, request: "GET /i/?get=f_2089 HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "odroid:1081"
```

**Comment by Alkarex** [comment]
@rezad1393 Remember to provide information about your system (OS, install type, versions...). In particular, make sure you are running the newest version of FreshRSS.

**Comment by rezad1393** [comment]
sorry.
last version of freshrss  1.23.1 
os archlinux 
type ?? (just unzipped the release) and webserver is nginx.

**Comment by Alkarex** [comment]
@rezad1393 The error you get is a sign that the code you are running is older than FreshRSS 1.23.0. If you are deploying / updating by hand, maybe you have not deployed all files properly.

**Comment by rezad1393** [comment]
in the last updates, the instance would freeze after a while so maybe those cause an incomplete upgrade.
the version shown in about is the latest one though.

can I just download the zip here and overwrite mine?

**Comment by Alkarex** [comment]
> can I just download the zip here and overwrite mine?

Yes

**Comment by rezad1393** [comment]
I did the overwrite and still i get the error.
