### ISSUE TITLE
[CustomCSS] Error 403

### ISSUE THREAD

**Issue by michaudg** [FreshRSS/Extensions#19]
Tout d'abord, merci pour cette extension.

Lorsque le bouton "Valider" est cliqué, la page « /i/?c=error » s'affiche, l'erreur ci-dessous apparaît et la session est déconnectée. Une fois reconnecté, les modifications apportées au CSS n'ont pas été sauvegardées.

```
Error 403 - Forbidden
You don’t have permission to access this page [HTTP_REFERER=]
```

La configuration NGINX recommandée dans votre documentation d'installation est en place.

Le fichier access.log nginx indique:
```
[12/Oct/2017:19:16:38 -0400] "POST /i/?c=extension&a=configure&e=Custom%2BCSS HTTP/1.1" 302 5 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
[12/Oct/2017:19:16:38 -0400] "GET /i/?c=error HTTP/1.1" 403 4000 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
```

**Comment by Alkarex** [comment]
Bonjour,
Quelle version de FreshRSS utilisez-vous ? Et quel navigateur ?
Comme visible dans le message d'erreur ainsi que dans la première ligne de votre log, il semblerait que votre navigateur bloque son `Referer` même sur le même domaine (ce qui diminue la sécurité). Pourriez-vous tester avec un autre navigateur ?

**Comment by michaudg** [comment]
FreshRSS: 1.8.0
Navigateur: Firefox 56, AdBlocker désactivé

Le même problème est présent sous Chromium 61.

**Comment by Alkarex** [comment]
Et votre Chromium est bien sans extension ?
Il semble qu'il y ait quelque chose qui altère vos entêtes HTTP. Pas de proxy ou autre ?
Pourriez-vous éventuellement me faire un compte de test ?

**Comment by michaudg** [comment]
Pas de proxy, j'accède directement au serveur.

La seule extension Chromium active est "Intégration à GNOME Shell".

Je suis passé de NGINX à Apache et le problème est le même.

Dites-moi ce que vous avez besoin comme accès au serveur et ça me fera plaisir de vous mettre en place ce qu'il faut.

**Comment by michaudg** [comment]
Problème résolu.

Ma version de l'extension CustomCSS avait dû être cloné il y a très longtemps (plus d'un an) car le problème n'est plus présent en reclonant le dépôt Extensions actuel.

Désolé pour la fausse alerte et merci d'avoir pris le temps de m'aider.
