### ISSUE TITLE
[Image Proxy] "https://" should be replaced by "ssl:"

### ISSUE THREAD

**Issue by mathieumd** [FreshRSS/Extensions#20]
The proxy configured by default ([images.weserv](https://images.weserv.nl/)) cannot handle `https://` scheme (according to andrieslouw/imagesweserv#33).

You need to replace `https://` by `ssl:` like this:
- KO: https://images.weserv.nl/?url=https://freshrss.org/images/freshrss_logo.png (_Error 404: Server couldn't parse the ?url= that you were looking for, because it isn't a valid url._)
- OK: https://images.weserv.nl/?url=ssl:freshrss.org/images/freshrss_logo.png

Maybe it could be implemented in the fonction [line 24 in xExtension-ImageProxy/extension.php](../blob/master/xExtension-ImageProxy/extension.php#L24)?

**Comment by Frenzie** [comment]
You're saying you also want https images proxied?

**Comment by mathieumd** [comment]
Wasn't thinking straight that day, I guess! 🤔 Was reading images.weserv doc and went hot about this "missing feature", but it was too early in the morning... ^^
It could be used to prevent webmasters to know when we are reading our feeds, I guess, but I'm not sure if it's really a concern. Closing this one. Sorry for the noise!
