### ISSUE TITLE
Extension: Mark previous as read

### ISSUE THREAD

**Issue by kalvn** [FreshRSS/Extensions#204]
Hello,

This is just to inform you that I created a tiny extension that adds a button *Mark previous as read* into the footer of each entry.

https://github.com/kalvn/freshrss-mark-previous-as-read

It mimics the features that is triggered by `ALT+R` but makes it available for mobile devices where shortcuts can't be used.

The main goal was to benefit from something similar to Feedly's "mark above as read".

*Important point*: it only targets entries belonging to the feed of the current entry.

I've used it for a couple of days and it works pretty well so far. Feedbacks welcome :)

**Comment by Alkarex** [comment]
Nice 👍🏻 
Please add it to our list (and potentially readme):
https://github.com/FreshRSS/Extensions/blob/master/repositories.json

**Comment by kalvn** [comment]
Done, thanks :)

https://github.com/FreshRSS/Extensions/pull/205
