### ISSUE TITLE
YouTube: new maintainer or migrate here?

### ISSUE THREAD

**Issue by kevinpapst** [FreshRSS/Extensions#216]
Hi @Alkarex and everyone else from the Community!

I wanted to ask if someone wants to take over maintainership of the YouTube extension.
OR if we could/should move the code to this repository here, so more eyes and hands are available to keep it alive.

I don't have the resources to take care of the plugin and I am going to archive it. 

Seeing that [this commit was merged](https://github.com/FreshRSS/Extensions/commit/b2abcc23e4bccaa41129ae6e43c5e03f39791f13), instead of once contacting me beforehand and/or trying to get commit permissions [on my repo](https://github.com/kevinpapst/freshrss-youtube) I get the impression that this might not even be necessary, but would be good to get some feedback anyway.

Thanks for still working on FreshRSS after all these years 👍

**Comment by Frenzie** [comment]
A PR like that without trying to communicate with you is a bit weird. :-/

I'm fine putting it in this repo, but any maintenance from me would be shallow (i.e., the occasional update if needed to work with FreshRSS sure, but if YT greatly changed probably not unless it somehow piqued my interest.

**Comment by Alkarex** [comment]
Hello,
It is hard having an overview of third-party extensions and remembering which is actively maintained or not, so in particular for popular extensions, it could indeed be good to move them to https://github.com/FreshRSS/Extensions to facilitate collaboration and avoid forks (which I also dislike)

**Comment by Alkarex** [comment]
For reference:
* https://github.com/FreshRSS/Extensions/pull/134#issue-1204696043
* My comment on a related case https://github.com/FreshRSS/Extensions/issues/190#issuecomment-1855667402

**Comment by Alkarex** [comment]
And example of maintenance issue https://github.com/FreshRSS/FreshRSS/issues/6190

**Comment by kevinpapst** [comment]
Awesome, thanks for your blazing fast feedback!

I am using a FreshRSS installation hosted by a friend, so I don't even have a dev system around to take care of [issues like this one here](https://github.com/kevinpapst/freshrss-youtube/issues/22). 

Super simple to fix, but I am not applying any change without a test run before... 

I will prepare a commit to move it here and then we should check the commits on the fork and bring them in as well.

**Comment by kevinpapst** [comment]
Closing, PR in #217
