### ISSUE TITLE
Github Action job with an annotation: `The `set-output` command is deprecated and will be disabled soon. 

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/Extensions#219]
```
The `set-output` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files.
For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

![grafik](https://github.com/FreshRSS/Extensions/assets/1645099/6c82c548-b2bb-427d-bc49-cdef3588d280)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/Extensions/actions/runs/8279809643

https://github.com/FreshRSS/Extensions/blob/dc3fbfb05ea4de32b2e5d1ffd95494c6ea226297/.github/workflows/generate.yml#L26-L30

**Comment by Alkarex** [comment]
Should be fixed by https://github.com/FreshRSS/Extensions/pull/220
