### ISSUE TITLE
ttrss-reader says "not found" despite ttrss-api installed

### ISSUE THREAD

**Issue by nousernameavailableanymore** [FreshRSS/Extensions#226]
I installed the extension, enabled api-access (readrops works fine) and set up the URL as described in the github:
https://github.com/FreshRSS/Extensions/tree/master/xExtension-TTRSS_API

However, the reader app still says: 404 not found

Is there any way to get ttrss-reader to work with freshrss?

**Comment by math-GH** [comment]
see #75 too

**Comment by nousernameavailableanymore** [comment]
> see #75 too

So there is no way to get ttrss-reader to work with freshrss?

**Comment by Alkarex** [comment]
I have not tried, but it would require some work on https://github.com/FreshRSS/FreshRSS/pull/1526
If ttrss-reader supports 64-bit article IDs, it might be easy; if not, some more compatibility work would be needed, client side or server side.
Help welcome, if anyone is motivated.
In the meantime, there are several other apps available:
https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#apis--native-apps

**Comment by nousernameavailableanymore** [comment]
>  In the meantime, there are several other apps available: https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#apis--native-apps

While I appreciate the list, it seems to be really outdated.
"EasyRSS" has a checkmark in "Maintained & Developed" and was last updated in 2020.
"Readrops" even has two checkmarks and was last updated in 2021. It even has a bug, where you cannot mark articles as read, which never got fixed.
If any kind of software did not receive an update in the last 12 months, I personally would consider it as "not maintained" anymore.
That does not necessarily have to be a problem, but if there are major bugs (like in the case of Readrops) that never get fixed, its rather annoying.

So yeah, the table that documents the maintenance status does not seem to be maintained anymore...

**Comment by Frenzie** [comment]
EasyRSS is maintained. It hasn't received any commits because it doesn't need any commits. What it's not is developed, which is why it only has one checkmark.

Readrops hasn't received any commits in the last 12 hours, so I guess it's unmaintained now. How dare the last commit be an eternal 15 hours ago. ;-)

**Comment by nousernameavailableanymore** [comment]
> Readrops hasn't received any commits in the last 12 hours, so I guess it's unmaintained now. How dare the last commit be an eternal 15 hours ago. ;-)

Who cares how many _commits_ there were at any time. There could be a million commits in a day and it would still be pointless when no new version is being released.
The last version has been released in 2021, so in my book, Readrops is pretty much dead.

That being said, I must have started with the worst option of the readers, as both "Focus Reader" and "Feed me" are both perfectly fine.
Also, both Readers are "free" (as in free beer), in contrast to what the overview table says.
There is a subscription tier in "Focus Reader", however, this only gives you some AI crap and the ability to download the whole web page as article.

So yeah, I guess this can be closed here. "Feed me" and  "Focus Reader" are both better than ttrss-reader.

**Comment by math-GH** [comment]
There is an actual fork of TTRSS reader:


see here: https://github.com/nilsbraden/ttrss-reader-fork

last update in the Google Play Store: February 2024 https://play.google.com/store/apps/details?id=org.ttrssreader&hl=en&gl=US

see here too: https://www.nilsbraden.de/TTRSS-Reader/

**Comment by nousernameavailableanymore** [comment]
> There is an actual fork of TTRSS reader:

I didnt even know that there was any other version 🤣
So yes, this is the version I have been using.

However, compared to Focus Reader (which I use now and which looks very modern) the UI is rather outdated, it lacks some features, the sync process is much slower for some reason (only takes like 1 or 2 seconds with Focus Reader and around 10 seconds with ttrss reader) and yeah well, it only seems to support the software by some very right wing, borderline fascist russian developers...

Having played around with FreshRSS a bit in the last two weeks, it seems somewhat superior to TTRSS, especially due to the extensions.
