### ISSUE TITLE
Error when using the ImageProxy plugin

### ISSUE THREAD

**Issue by m00nwtchr** [FreshRSS/Extensions#230]
```
[Wed Apr 10 09:07:54.250753 2024] [php:error] [pid 890] [client fd00:4c3::1:0] PHP Fatal error:  Uncaught Error: Call to undefined method FreshRSS_Context::hasSystemConf() in /var/www/FreshRSS/extensions/xExtension-ImageProxy/extension.php:15\nStack trace:\n#0 /var/www/FreshRSS/lib/Minz/ExtensionManager.php(263): ImageProxyExtension->init()\n#1 /var/www/FreshRSS/lib/Minz/ExtensionManager.php(279): Minz_ExtensionManager::enable()\n#2 /var/www/FreshRSS/app/FreshRSS.php(64): Minz_ExtensionManager::enableByList()\n#3 /var/www/FreshRSS/p/i/index.php(55): FreshRSS->init()\n#4 {main}\n  thrown in /var/www/FreshRSS/extensions/xExtension-ImageProxy/extension.php on line 15
```

**Comment by math-GH** [comment]
Hi, thanks for the reporting.
Could you please give us more information about your environment? 

- FreshRSS version: [e.g. 1.23.1]
- extension version: [e.g. 0.1]
- Database version: [e.g. Mysql 5.7, SQLite]
- PHP version: [e.g. PHP 8.1]
- Installation type: [e.g. Docker, Docker image source, git, Yunohost]
-Web server type: [e.g. Apache, nginx]
- Device: [e.g. iPhone13]
- OS: [e.g. Ubuntu 22.04, Win10, MacOS14]
- Browser: [e.g. Firefox 124]

**Comment by m00nwtchr** [comment]
Ok, I figured out what my issue was.
It turns out I had an incorrect volume mapping `freshrss_data:/var/www/FreshRSS` instead of `/var/www/FreshRSS/data` which kept FreshRSS from updating, which caused the incompatibility with the plugin.
