### ISSUE TITLE
[BUG] xExtension-TitleWrap Line wrapping is not enabled

### ISSUE THREAD

**Issue by kometchtech** [FreshRSS/Extensions#239]
The following pull request says that 1.24.0 is supported, but I actually tried it on the May 23, 2024 release (docker image) and the title wrapping was not enabled.

https://github.com/FreshRSS/Extensions/pull/232

- It is enabled in freshrss as follows. Version 0.3.0.

![image](https://github.com/FreshRSS/Extensions/assets/5137077/76ae1c68-bfaa-48fa-84ca-cc2c2af3d49c)

- You can confirm that title wrapping is not enabled.

![image](https://github.com/FreshRSS/Extensions/assets/5137077/319e7821-b07e-47e9-b2b2-553b30e3c2b9)

**Comment by math-GH** [comment]
Are any other extensions enabled?

**Comment by kometchtech** [comment]
Sorry for the late reply.

The only extension I have enabled is Title-wrap.

However, I looked into it afterwards and it seems that the symptom only occurs in my Firefox custom browser.

When I switched to Chrome or the official Firefox, I confirmed that the title is displayed with wrap without any problem.

Sorry for my hasty report.
