### ISSUE TITLE
[xExtension-ShareByEmail] does not work with FreshRSS1.25.0-dev

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/Extensions#263]
`id` is empty

![grafik](https://github.com/user-attachments/assets/fddee57a-b3bc-43de-9588-5a01dfa6e2c6)

![grafik](https://github.com/user-attachments/assets/842ff140-1cc1-48e9-9104-26ea1e78934a)

**Comment by math-GH** [comment]
root cause

https://github.com/FreshRSS/FreshRSS/blob/20c1d06e6258b211fb208fc885ad4e2d6e4a4094/app/Models/Share.php#L239-L253
`$this->id` is `null` but it should not.

**Comment by Alkarex** [comment]
> root cause
> 
> https://github.com/FreshRSS/FreshRSS/blob/20c1d06e6258b211fb208fc885ad4e2d6e4a4094/app/Models/Share.php#L239-L253 `$this->id` is `null` but it should not.

Is it a regression in `edge`?

**Comment by Alkarex** [comment]
I think it is a regression due to https://github.com/FreshRSS/FreshRSS/pull/6751

**Comment by math-GH** [comment]
> I think it is a regression due to [FreshRSS/FreshRSS#6751](https://github.com/FreshRSS/FreshRSS/pull/6751)

`main.js` is JavaScript. But it is a PHP issue here.

**Comment by Alkarex** [comment]
> > I think it is a regression due to [FreshRSS/FreshRSS#6751](https://github.com/FreshRSS/FreshRSS/pull/6751)
> > That was my first thought too.
> > But `main.js` is JavaScript. It is a PHP issue here.

That PR also changes the PHP code

**Comment by math-GH** [comment]
Great, that helped. I did not notice that this `phtml` has relevant PHP code. Fix is created
