### ISSUE TITLE
Wallabag button extension

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/Extensions#42]
Just something I half-randomly came across that could be added to the JSON.

https://git.n7r.de/nrb/freshrss-wallabag

> This FreshRSS adds a button to each article
which adds the respective article to your
Wallabag installation.
FreshRSS already comes with a pretty good integration with Wallabag
through its share feature. The author of this plugin was annoyed by the
fact that the share feature is just a simple link, which means that a
new tab opens when a article is added to Wallabag. This extension uses
the Wallabag API and sends the request from the server side. This means
that your workflow of skipping through articles is not interrupted when
you add an article to Wallabag.
This extension is only compatible with Wallabag v2.

**Comment by Alkarex** [comment]
Looks good :-)

**Comment by lapineige** [comment]
:up: ?

**Comment by Alkarex** [comment]
The link does not seem to work anymore (502 Bad Gateway). Otherwise PR welcome with a working link

**Comment by math-GH** [comment]
any news or should we close it?

**Comment by lapineige** [comment]
Not on my side. Let's close ?
