### ISSUE TITLE
[xExtension-CustomCSS] Add notice to create styles.css

### ISSUE THREAD

**Issue by husim0** [FreshRSS/Extensions#51]
Hello,
It's not mentioned anywhere that we have to create manually static/style.css and give it www-data permissions (33:33). Could be great to mention it.
Thank you :-)

**Comment by Frenzie** [comment]
To be clear, the installation says that `Permissions on users directory are good.`? (Under Settings → Installation checking.)

**Comment by husim0** [comment]
My installation is a bit special because I'm using Docker and I mounted a directory to put extensions in it and at first, indeed, rights were not good because extensions dir was owned by root and not by www-data. 

But then I changed the permissions and it wasn't able neither to create the `static/styles.css` that doesn't exist in the repo. I don't know if it's supposed to created automatically or if it has to be created manually (my guess). Until I created the file `static/styles.css` (with www-data owner), the page extension said to me "Permissions are wrong" or something like that.

Thank you :)

**Comment by aledeg** [comment]
@husim0 Have you tried again? Is this still happening?
I am an env similar to yours and I have no problem with permissions. Here is the command I am using:
```
make start extensions="/path/to/extension/1 /path/to/extension/2 /path/to/extension3"
```
This uses the `Makefile` from FreshRss.

**Comment by math-GH** [comment]
@husim0 : Any news?

**Comment by math-GH** [comment]
lets close it
