### ISSUE TITLE
style is not active

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/Extensions#52]
I have installed CustomCSS extension and added 
```
.tree-folder-items {background: #F7F7F7;}
.aside {background: #F7F7F7;}
```
But the style seems not to overwrite the background color of the active theme (Swage). The style information is saved as style.username.css in static on filesystem.

**Comment by Frenzie** [comment]
You'll either need to add more specificity or you could always try taking a shortcut with `!important` (bad while *writing* themes; generally okay to override specifics).

**Comment by Offerel** [comment]
Could you please add a example for the mentioned sidebar, so that I can can change the background? Currently I use style inspector in Firefox (F12 key) to find style to change.

**Comment by Frenzie** [comment]
I wrote that based on your described symptoms, but having checked out that theme, your problem must be that you're not refreshing the page. You might need to use something like Ctrl+F5.

**Comment by Offerel** [comment]
I have no idea, whats going on. Currently I'm on the dev branch, maybe thats' the problem, i don't know know if there is changed something regarding to styles in dev, i use it only because of the login via e-mail address. I didn't see any error message on server side, nor anything regarding a error in Firefox console (didn't check Chrome since i didn't use it). And yes, i used Ctrl + F5, private mode and a clean new profile to. Also on another Laptop the style didn't show up. I see that style is saved to is saved to _/var/www/freshrss/extensions/xExtension-CustomCSS/static/style.user@mydomain.de.css_, but that's all.

The only idea, when i look at the path now is, that the username in form of the e-mail address is the problem? Could this be a problem? I will test it with current stable again.

**Comment by Offerel** [comment]
OK, THEN. I'm really ashamed now. I didn't see the button "deactivated"... I'm really sorry to have bothered you with that. Please forget the issue, the only issue is my own stupidity...

**Comment by Frenzie** [comment]
We all make mistakes, and hopefully learn from them. ;-)
