### ISSUE TITLE
CustomCSS not working with FreshRSS 1.4.0

### ISSUE THREAD

**Issue by michaudg** [FreshRSS/Extensions#6]
Hi,
 I installed the custom CSS extension on FreshRSS 1.4.0 and I try to apply the rule below. When I press the Validate button, the field become blank and the rule doesn't work.

.aside_feed {
width: 200px;
}

Thank you.

**Comment by michaudg** [comment]
I found the problem. The ACL to the static directory was wrong and PHP was not able to write inside it.
The extension works great.

Thank you.

**Comment by Alkarex** [comment]
Ok :-)
