### ISSUE TITLE
Make a reference to greader "redate" extension ?

### ISSUE THREAD

**Issue by javerous** [FreshRSS/Extensions#72]
Hi,

Following this ticket https://github.com/FreshRSS/FreshRSS/issues/2759 and this PR https://github.com/FreshRSS/FreshRSS/pull/2773, I created this extension: https://github.com/javerous/freshrss-greader-redate

At first, I wanted to keep it private, but I thought it can perhaps be used by someone else. Do you see any interest to make a reference to it on the community page (via _extensions.json_ file) ?

I'm not sure it has the quality grade expected to be on this page, and I'm not sure it worth putting it there at all… Then feel free to reject ;)

As a very short remember, the idea is to change fetching date by publishing date in greader API for clients like Reeder or EasyRSS which use only crawling date. It requires master / 1.16 version of FreshRSS to work.

[EDIT] The point is it's mainly a workaround extension. It's possible that those clients fix how they are using dates from greader at some point, making this extension _de-facto_ obsolete.

**Comment by Frenzie** [comment]
There's plenty of stuff that'll become obsolete for some reason or other. I don't see that as an issue. ;-)

**Comment by Alkarex** [comment]
@javerous Please send a PR with a reference to your extension

**Comment by javerous** [comment]
I created the PR https://github.com/FreshRSS/Extensions/pull/79
