### ISSUE TITLE
Add ability to add notes and keyword tags

### ISSUE THREAD

**Issue by amereservant** [FreshRSS/Extensions#8]
First, I would like to say thank you for this script!
I needed a feed aggregator to combine my news sources and store the articles so I could later find them via a quick search.  This is much easier than trying to write my own.  However the other feature I need is the ability to add notes to an article as well as assign keywords for topical reference.  Some of the feeds I want to use will contain media enclosures (podcasts) and very little detail in the descriptions, so being able to add this data manually will make it easier to find a particular episode later on.

A couple of other requests would be the ability to selectively delete episodes from a feed that I do not want and the option to disable deleting old feed items.  A couple of ways to help avoid overpopulating the database might be:
- An option to set a feed limit and then produce some sort of warning when that limit is close to being reached.  If the limit is reached, no further feed items will be downloaded until that number is set higher or the number of stored feed items for that feed is reduced.
- Ability to archive old posts, but keep the notes/keywords and a reference to the archive file so it can be restored if needed.  Archiving could even me an automated function based on reaching the max items number or using an "older than" option.

Anyways, thanks again.

**Comment by Alkarex** [comment]
Hello @amereservant 
I am glad you like FreshRSS :-)
Those are interesting suggestions. I suggest you take a look at the open source project https://www.wallabag.org , which might cover some of your needs.
FreshRSS supports sending an article to your Wallabag instance. Combining FreshRSS + Wallabag is quite usual.

**Comment by amereservant** [comment]
Hey @Alkarex
Thank you for the feedback and I really appreciate the wallabag suggestion!  That was actually what I was looking for at first, but found FreshRSS instead.  The reason I did want a custom RSS aggregator is because Facebook isn't a reliable way to see news since their algorithms tend to not show the news that I want to see.  Since most of the places I read news from have RSS feeds, it just made sense to use something like FreshRSS, especially with it's ability to search through past articles.  Facebook really sucks at that part.

Oddly enough, Wallabag doesn't allow you to edit the contents of the article either, just the title.  *sighs*  Both are excellent tools that I'll use for referencing past articles I've read, which I do quite often in conversations, so I really appreciate your suggestions.

**Comment by aledeg** [comment]
I think we can close this issue since Wallabag now supports annotation.
