### ISSUE TITLE
Share By Email Extension > root@localhost

### ISSUE THREAD

**Issue by strasbourgcurieux** [FreshRSS/Extensions#85]
Hello
it would be interesting to be able to replace the email sent "root@localhost" with an email of our choice.
Kind regards

Bonjour
il serait intéressant de pouvoir remplacer le mail s’envoie "root@localhost" par un mail de notre choix.
Cordialement

**Comment by Alkarex** [comment]
Hello,
In your `./data/config.php`, check the SMTP section
https://github.com/FreshRSS/FreshRSS/blob/399ce395795c2c0d7ada796f097eca646f269716/config.default.php#L172-L181

**Comment by strasbourgcurieux** [comment]
Hello
Thank you for your information.
I suggest that the info be present in the window "manage" for future users

Bonjour
Merci pour votre info.
Je suggère que l'info soit  présente dans la fenêtre " gerer " pour les futurs utilisateurs
