### ISSUE TITLE
Prevent proxying of icons [xExtension-ImageProxy]

### ISSUE THREAD

**Issue by subic** [FreshRSS/Extensions#9]
Hi, as far as I understand proxying of favicons is unnecessary (even when using ssl) - they are "proxied" by f.php. It might be good idea to hardcode this exception as the load times (without local cache) can take a long time reverse proxy (ie. 30s until fail for a png icon file on each load).

**Comment by Alkarex** [comment]
@Frenzie Could you please have a look?

**Comment by Frenzie** [comment]
I'm afraid I don't follow. The ImageProxy extension only acts on content. If there's a problem it would be with f.php.

**Comment by subic** [comment]
Yes, upon further investigation it is probably an issue with multiple concurrent connections timing out through f.php. The png file led me to believe the problem might be related to image proxy, but I was wrong. Consider the issue resolved, sorry for the confusion.
