### ISSUE TITLE
Keep Foldder State

### ISSUE THREAD

**Issue by Zazou89** [FreshRSS/Extensions#90]
Hello,
The extension seems doesn't work anymore. After a refresh arrow is displayed but not feed inside : 

![image](https://user-images.githubusercontent.com/206181/96309608-f66ab000-1005-11eb-92ba-a3f454feb552.png)

**Comment by Alkarex** [comment]
See related effort as a core feature https://github.com/FreshRSS/FreshRSS/pull/3185#issuecomment-710084039

**Comment by Alkarex** [comment]
Implemented as a core feature. Tests welcome https://github.com/FreshRSS/FreshRSS/pull/3185
