### ISSUE TITLE
Email Feed

### ISSUE THREAD

**Issue by d7eeem** [FreshRSS/Extensions#91]
i am just wondering if it is possible to get an email feed like when you sign up for a mailing list you get it in your dashboard,
Like what feedbin is doing they provide you with an email address when you sign up to mailing list you but the feedbin email and you get the mail in your feed.

**Comment by Alkarex** [comment]
Something like https://kill-the-newsletter.com ?

**Comment by d7eeem** [comment]
> https://kill-the-newsletter.com

Yes That exactly it but with my email address.
