### ISSUE TITLE
Hello, I have made a couple of extensions 

### ISSUE THREAD

**Issue by PAHXO** [FreshRSS/Extensions#96]
Hi there,

I have made a couple of extensions, but I don't know where exactly to share them

Here they are
https://github.com/PAHXO/Fancy-FreshRSS-Extensions

The MediaArchiver extension is **Very Experimental** and it exposes all the images/videos to (/p/i/) so only use it on a local server.

Feel free to give me your opinions

**Comment by Frenzie** [comment]
Looks cool. Should be fine to put in the READM and extensions.json here. :-)

**Comment by PAHXO** [comment]
feel free to do so
